// Generated by tool/generate_changelog.dart from CHANGELOG.md. Do not edit by hand.

class ChangelogEntry {
  const ChangelogEntry({
    required this.version,
    required this.date,
    required this.items,
  });

  final String version;
  final String date;
  final List<String> items;
}

const List<ChangelogEntry> changelogEntries = [
  ChangelogEntry(
    version: '0.6.2',
    date: '2026-07-08',
    items: [
      'Add Linux x64 support to the generated Homebrew formula.',
      'Add a release install smoke test that verifies packaged binaries before drafting a GitHub Release.',
    ],
  ),
  ChangelogEntry(
    version: '0.6.1',
    date: '2026-07-07',
    items: [
      'Fix Android ADB discovery on Linux by checking `\$HOME/Android/Sdk` and falling back to `adb` on `PATH` when no SDK-managed binary is present.',
      'Stop treating all Android physical devices as fully booted when `adb devices -l` reports intermediate states such as `unauthorized` or `offline`.',
      'Restore SSH terminal and TTY state on Linux after quitting remote sessions.',
    ],
  ),
  ChangelogEntry(
    version: '0.6.0',
    date: '2026-06-26',
    items: [
      'Add custom plugin support via the `plugins:` section of `~/.simutil/settings.yaml`: register external shell-command tools (each with one or more commands) and run them from the app with `p` (plugin → command → execute) or a direct command shortcut, without changing code.',
      'Add `e` key to open `~/.simutil/settings.yaml` in the OS default editor (macOS, Linux, Windows).',
      'Route plugin availability probes through `CommandExec` instead of calling `Process.run` directly.',
      'Merge plugin configuration into `~/.simutil/settings.yaml` (settings scalars + `plugins:` section in one file).',
      'Migrate the built-in scrcpy integration to the YAML plugin registry (a default config with scrcpy is generated on first launch).',
      'Prevent device refresh from hanging forever when a simulator or device lookup stalls.',
      'Fix `Device.fromJson` reading the `os` field from the wrong key, which made deserialization always throw.',
    ],
  ),
  ChangelogEntry(
    version: '0.5.0',
    date: '2026-05-02',
    items: [
      'Add Windows PowerShell installer command (`install.ps1`) to README installation section.',
      'Refactor Wi-Fi pairing flow to match Android Studio: discover pairing-code endpoints first, require code entry after selecting a discovered device, then resolve and connect to the post-pair ADB connect endpoint.',
      'Fix text color in dialogs and panels to avoid wrong overlay effect.',
    ],
  ),
  ChangelogEntry(
    version: '0.4.1',
    date: '2026-04-11',
    items: [
      'Fix incorrect way to terminate app.',
    ],
  ),
  ChangelogEntry(
    version: '0.4.0',
    date: '2026-04-05',
    items: [
      'Add Logcat dialog for launching Android emulators / devices.',
    ],
  ),
  ChangelogEntry(
    version: '0.3.2',
    date: '2026-03-28',
    items: [
      'Fixed iOS devices discovery when device is not connected.',
      'Fixed dialogs and panels color',
    ],
  ),
  ChangelogEntry(
    version: '0.3.1',
    date: '2026-03-26',
    items: [
      'Add macOS Intel support.',
    ],
  ),
  ChangelogEntry(
    version: '0.3.0',
    date: '2026-03-23',
    items: [
      'Add `shutdown` action for Android emulators and iOS simulators.',
      'Change default keymap for `launch` and `launch with option` actions for Android emulators.',
    ],
  ),
  ChangelogEntry(
    version: '0.2.1',
    date: '2026-03-21',
    items: [
      'Fix wrong focus when initializing app.',
    ],
  ),
  ChangelogEntry(
    version: '0.2.0',
    date: '2026-03-21',
    items: [
      'Add iOS devices discovery.',
      'Add `SelectionArea` in Detail panel to allow user to select.',
      'ADB tools can be accessed from any panel.',
      'Replace Android emulator id with serial id when device is launching.',
    ],
  ),
  ChangelogEntry(
    version: '0.1.0',
    date: '2026-03-20',
    items: [
      'Support Android physical devices',
      'Reopen ADB tools menu',
    ],
  ),
  ChangelogEntry(
    version: '0.0.4',
    date: '2026-03-17',
    items: [
      'Temporarily hide ADB Tools menu',
      'Fix build error',
    ],
  ),
  ChangelogEntry(
    version: '0.0.3',
    date: '2026-03-17',
    items: [
      'Temporarily hide ADB Tools menu',
    ],
  ),
  ChangelogEntry(
    version: '0.0.2',
    date: '2026-03-16',
    items: [
      'Add version command',
    ],
  ),
  ChangelogEntry(
    version: '0.0.1',
    date: '2026-03-15',
    items: [
      'Initial release',
    ],
  ),
];

ChangelogEntry? changelogEntryForVersion(String version) {
  for (final entry in changelogEntries) {
    if (entry.version == version) return entry;
  }
  return null;
}
