import 'dart:io';

class ParsedChangelogEntry {
  const ParsedChangelogEntry({
    required this.version,
    required this.date,
    required this.items,
  });

  final String version;
  final String date;
  final List<String> items;
}

final _versionHeader = RegExp(r'^## \[(\d[\w.\-]*)\] - (\d{4}-\d{2}-\d{2})');
final _bulletLine = RegExp(r'^- (.*)$');

List<ParsedChangelogEntry> parseChangelog(String content) {
  final entries = <ParsedChangelogEntry>[];
  String? version;
  String? date;
  var items = <String>[];

  void addCurrentEntry() {
    if (version == null || date == null) return;
    entries.add(
      ParsedChangelogEntry(version: version, date: date, items: items),
    );
  }

  for (final line in content.split('\n')) {
    if (line.startsWith('## [')) {
      addCurrentEntry();
      final header = _versionHeader.firstMatch(line);
      version = header?.group(1);
      date = header?.group(2);
      items = <String>[];
      continue;
    }

    final bullet = _bulletLine.firstMatch(line);
    if (version != null && bullet != null) {
      items.add(bullet.group(1)!);
    }
  }
  addCurrentEntry();

  return entries;
}

String _dartString(String value) =>
    "'${value.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

String generateChangelogSource(List<ParsedChangelogEntry> entries) {
  final buffer = StringBuffer()
    ..writeln(
      '// Generated by tool/generate_changelog.dart from CHANGELOG.md. Do not edit by hand.',
    )
    ..writeln()
    ..writeln('class ChangelogEntry {')
    ..writeln('  const ChangelogEntry({')
    ..writeln('    required this.version,')
    ..writeln('    required this.date,')
    ..writeln('    required this.items,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String version;')
    ..writeln('  final String date;')
    ..writeln('  final List<String> items;')
    ..writeln('}')
    ..writeln()
    ..writeln('const List<ChangelogEntry> changelogEntries = [');

  for (final entry in entries) {
    buffer
      ..writeln('  ChangelogEntry(')
      ..writeln('    version: ${_dartString(entry.version)},')
      ..writeln('    date: ${_dartString(entry.date)},')
      ..writeln('    items: [');
    for (final item in entry.items) {
      buffer.writeln('      ${_dartString(item)},');
    }
    buffer
      ..writeln('    ],')
      ..writeln('  ),');
  }

  buffer
    ..writeln('];')
    ..writeln()
    ..writeln('ChangelogEntry? changelogEntryForVersion(String version) {')
    ..writeln('  for (final entry in changelogEntries) {')
    ..writeln('    if (entry.version == version) return entry;')
    ..writeln('  }')
    ..writeln('  return null;')
    ..writeln('}');

  return buffer.toString();
}

Future<void> main() async {
  final changelog = File.fromUri(Platform.script.resolve('../CHANGELOG.md'));
  final output = File.fromUri(
    Platform.script.resolve('../lib/data/changelog_entries.dart'),
  );
  final entries = parseChangelog(await changelog.readAsString());

  await output.parent.create(recursive: true);
  await output.writeAsString(generateChangelogSource(entries));
}
