import 'dart:io';

final _versionLine = RegExp(r'^version:\s*(\S+)\s*$', multiLine: true);

/// Reads the top-level `version:` from [pubspec] content.
String parseVersion(String pubspec) {
  final match = _versionLine.firstMatch(pubspec);
  if (match == null) {
    throw const FormatException('pubspec.yaml has no top-level version');
  }
  return match.group(1)!;
}

/// Dart source for `simutil`'s generated `lib/src/version.dart`.
String generateVersionSource(String version) =>
    '// Generated by tool/generate_version.dart from pubspec.yaml. '
    'Do not edit by hand.\n\n'
    '/// SimUtil app version (`packages/simutil/pubspec.yaml`).\n'
    "const packageVersion = '$version';\n";

Future<void> main() async {
  final pubspec = File.fromUri(Platform.script.resolve('../pubspec.yaml'));
  final output = File.fromUri(
    Platform.script.resolve('../lib/src/version.dart'),
  );
  final version = parseVersion(await pubspec.readAsString());
  await output.writeAsString(generateVersionSource(version));
}
