name: simutil_core
description: Core models and process execution for SimUtil.
version: 1.0.0
homepage: https://github.com/dungngminh/simutil
repository: https://github.com/dungngminh/simutil/tree/main/packages/simutil_core
issue_tracker: https://github.com/dungngminh/simutil/issues

environment:
  sdk: ^3.11.0

resolution: workspace

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
